In [6]:
import numpy as np
import time


def task2(n, f_type):

    def task_default():
        pattern = [[(i + j) % 2 for j in range(n)] for i in range(n)]

        matrix = [[0 for _ in range(n)] for _ in range(n)]

        matrix[0:n:2] = pattern[0:n:2]
        matrix[1:n:2] = pattern[1:n:2]
        return matrix

    def task_numpy():
        print([[(i + j) % 2 for j in range(n)] for i in range(n)])

        matrix = np.zeros((n, n))

        matrix[1::2, ::2] = 1
        matrix[::2, 1::2] = 1

        return matrix

    f = {'default': task_default, 'numpy': task_numpy}

    return f[f_type]


def task4(n, m, f_type):

    def task_default():
        return [[i if j == 0 else 0 for i in range(n)] for j in range(m)]

    def task_numpy():
        matrix = np.zeros((m, n))
        matrix[0] = np.arange(n)
        return matrix

    f = {'default': task_default, 'numpy': task_numpy}

    return f[f_type]


def task5(n, f_type):

    def task_default():
        return [[0 if j % 2 == 1 else 1 for _ in range(n)] for j in range(n)]

    def task_numpy():
        matrix = np.zeros((n, n))
        matrix[::2] = 1
        return matrix

    f = {'default': task_default, 'numpy': task_numpy}

    return f[f_type]


def task8(arr, f_type):

    def task_default():
        return len(list(filter(lambda x: x != 0, arr)))

    def task_numpy():
        return np.count_nonzero(arr)

    f = {'default': task_default, 'numpy': task_numpy}

    return f[f_type]


def task9(n, f_type):

    def task_default():
        return [i for i in range(n, -1, -1)]

    def task_numpy():
        return np.arange(n, -1, -1)

    f = {'default': task_default, 'numpy': task_numpy}

    return f[f_type]


def task12(n, f_type):

    def task_default():
        return [[0 if (j == 0 or i == 0 or j == n-1 or i == n-1) else 1 for i in range(n)] for j in range(n)]

    def task_numpy():
        matrix = np.zeros((n, n))
        matrix[1:-1, 1:-1] = 1

        return matrix

    f = {'default': task_default, 'numpy': task_numpy}

    return f[f_type]


def task13(f_type, n=8):

    def task_default():
        return task2(n, 'default')()

    def task_numpy():
        return [np.tile([1, 0], n // 2) if i % 2 else np.tile([0, 1], n // 2) for i in range(n)]

    f = {'default': task_default, 'numpy': task_numpy}

    return f[f_type]


def task15(n, f_type):

    def task_default():
        return [[0 if i % 2 == 0 else 1 for i in range(n)] for _ in range(n)]

    def task_numpy():
        matrix = np.zeros((n, n))
        matrix[::, 1::2] = 1
        return matrix

    f = {'default': task_default, 'numpy': task_numpy}

    return f[f_type]


def task19(n, f_type):

    def task_default():
        return [round(i / (n+1), 3) for i in range(1, n + 1)]

    def task_numpy():
        return np.around(np.arange(1, n+1) / (n+1), 3)

    f = {'default': task_default, 'numpy': task_numpy}

    return f[f_type]


def compare_time(f1, f2):
    start = time.time()
    result1 = f1()
    end = time.time()

    print(result1)
    print(f"Execution time: {end - start} seconds")

    start = time.time()
    result2 = f2()
    end = time.time()

    print(result2)
    print(f"Execution time: {end - start} seconds")

    print(f"Results are equal:{np.allclose(result1, result2)}")


compare_time(task2(5, 'default'), task2(5, 'numpy'))
compare_time(task4(3, 4, 'default'), task4(3, 4, 'numpy'))
compare_time(task5(5, 'default'), task5(5, 'numpy'))
compare_time(task8([1, 2, 0, 3, 0, 4, 0, 5], 'default'), task8([1, 2, 0, 3, 0, 4, 0, 5], 'numpy'))
compare_time(task9(5, 'default'), task9(5, 'numpy'))
compare_time(task12(5, 'default'), task12(5, 'numpy'))
compare_time(task13('default'), task13('numpy'))
compare_time(task15(5, 'default'), task15(5, 'numpy'))
compare_time(task19(10, 'default'), task19(10, 'numpy'))

[[0, 1, 0, 1, 0], [1, 0, 1, 0, 1], [0, 1, 0, 1, 0], [1, 0, 1, 0, 1], [0, 1, 0, 1, 0]]
Execution time: 0.0010001659393310547 seconds
[[0, 1, 0, 1, 0], [1, 0, 1, 0, 1], [0, 1, 0, 1, 0], [1, 0, 1, 0, 1], [0, 1, 0, 1, 0]]
[[0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]]
Execution time: 0.0019998550415039062 seconds
Results are equal:True
[[0, 1, 2], [0, 0, 0], [0, 0, 0], [0, 0, 0]]
Execution time: 0.0 seconds
[[0. 1. 2.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Execution time: 0.0 seconds
Results are equal:True
[[1, 1, 1, 1, 1], [0, 0, 0, 0, 0], [1, 1, 1, 1, 1], [0, 0, 0, 0, 0], [1, 1, 1, 1, 1]]
Execution time: 0.0 seconds
[[1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]]
Execution time: 0.0 seconds
Results are equal:True
5
Execution time: 0.0 seconds
5
Execution time: 0.0 seconds
Results are equal:True
[5, 4, 3, 2, 1, 0]
Execution time: 0.0 seconds
[5 4 3 2 1 0]
Execution time: 0.0 seconds
Results are equal:Tru

In [7]:
import numpy as np

# Defining the coefficients matrix and constant matrix
coefficients = np.array([[0, 1, -3, 4], [1, 0, -2, 3], [3, 2, 0, -5], [4, 3, -5, 0]])
constants = np.array([-5, -4, 12, 5])

# Solving the system of equations using Kramer's formulas
determinant = np.linalg.det(coefficients)

if determinant != 0:
    solutions = []
    for i in range(coefficients.shape[1]):
        # Replace the i-th column with the constants matrix
        temp = coefficients.copy()
        temp[:, i] = constants
        # Calculate the solution for the i-th variable using the determinant of the modified matrix
        solutions.append(round(np.linalg.det(temp) / determinant, 2))
    print("Kramer's solutions:", solutions)

    # Verifying the solutions using matrix multiplication
    mm_result = np.dot(coefficients, solutions)
    print("Matrix multiplication result:", mm_result)
    
    # Verifying the solutions using inverted matrix
    inv_result = np.dot(np.linalg.inv(coefficients), constants)
    print("Inverted matrix result:", inv_result)
    
    # Verifying the solutions using numpy.linalg.solve() function
    solve_result = np.linalg.solve(coefficients, constants)
    print("Solve function result:", solve_result)
    
    # Comparing all solutions using the numpy.allclose() function
    print("Are all solutions equal?", np.allclose(solutions, inv_result) and np.allclose(solutions, solve_result) and np.allclose(inv_result, solve_result))
else:
    print("The system of equations has no unique solutions.")


Kramer's solutions: [1.0, 2.0, 1.0, -1.0]
Matrix multiplication result: [-5. -4. 12.  5.]
Inverted matrix result: [ 1.  2.  1. -1.]
Solve function result: [ 1.  2.  1. -1.]
Are all solutions equal? True


In [8]:
import numpy as np
import time


def multiply(A, B):
    m, n = A.shape
    n, p = B.shape
    C = np.zeros((m, p))
    for i in range(m):
        for j in range(p):
            for k in range(n):
                C[i][j] += A[i][k] * B[k][j]
    return C


def add(A, B):
    m, n = A.shape
    C = np.zeros((m, n))
    for i in range(m):
        for j in range(n):
                C[i][j] += A[i][j] + B[i][j]
    return C


def subtract(A, B):
    m, n = A.shape
    C = np.zeros((m, n))
    for i in range(m):
        for j in range(n):
                C[i][j] += A[i][j] - B[i][j]
    return C


A = np.array([[7, 2, 0], [-7, -2, 1], [1, 1, 0]])
B = np.array([[0, 2, 3], [1, 0, -2], [3, 1, 1]])

start = time.time()

result1 = np.dot(np.subtract(np.linalg.matrix_power(A, 2), np.linalg.matrix_power(B, 2)), np.add(A, B))

end = time.time()

print(result1)
print(f"Execution time: {end - start} seconds")

start = time.time()

result2 = multiply(subtract(multiply(A, A), multiply(B, B)), add(A, B))

end = time.time()

print(result2)
print(f"Execution time: {end - start} seconds")

print(f"Results are equal:{np.allclose(result1, result2)}")



[[ 138   88   68]
 [-154 -100  -78]
 [ -14  -16  -12]]
Execution time: 0.0010001659393310547 seconds
[[ 138.   88.   68.]
 [-154. -100.  -78.]
 [ -14.  -16.  -12.]]
Execution time: 0.0009999275207519531 seconds
Results are equal:True
